"""IR → TypeScript code generation.

Emits a single ``client.ts`` containing the ``Result<T, E>`` envelope, one
``type`` declaration per shared component, the ``ApiRoutes`` interface, and
the ``createClient(...)`` call.

TS uses camelCase. Python uses snake_case. Tythe converts identifiers at the
codegen boundary — method names, type fields, arg keys all flip to camelCase
on the TS side. The runtime translates JSON keys both directions on the wire
so the Python server keeps seeing the snake_case shape it expects.
"""

from __future__ import annotations

import json
import keyword
import re
from collections.abc import Iterable
from pathlib import Path
from typing import Any, cast

from tythe._idents import to_camel as _to_camel
from tythe.ir import AppIR, ParamIR, RouteIR

HEADER_BANNER = """// AUTO-GENERATED by `tythe`. Do not edit by hand. Re-run `tythe dev`.
//
// Tour:
//   • api               — the typed client. `api.getIssue({ issueId: 1 })`.
//   • Domain types      — Issue, User, … Use directly in your own state/props.
//   • Errors            — discriminated on `kind`; switch on `.error.kind`.
//   • Enum consts       — `IssueStatus.Closed` instead of `"closed"` literals.
//   • Routes.X.{Args, Data, Error, Return}
//                       — per-route type aliases for helpers that need to
//                         reference a specific route's shape without retyping
//                         its unions by hand.

"""


def _render_header(ir: AppIR) -> str:
    # `Result<T, E>` is only emitted into type expressions for *unary* routes
    # with `@raises(...)`. Streaming routes signal errors as SSE `event: error`
    # frames that throw on the client side — they never appear as `Result<…>`
    # in the .ts output. Keep the import list minimal so the generated file has
    # no unused-import warnings.
    type_imports = ["CallOptions", "RouteDescriptor"]
    if any(route.raises and not route.streams for route in ir.routes):
        type_imports.insert(1, "Result")
    return (
        HEADER_BANNER
        + 'import { createClient } from "@tythe/ts";\n'
        + f'import type {{ {", ".join(type_imports)} }} from "@tythe/ts";\n'
    )


_DIVIDER_WIDTH = 78


def _section(title: str) -> str:
    """Emit a clean section heading: `// ── title ───────…`."""
    fill = max(3, _DIVIDER_WIDTH - len(title) - 6)
    return f"\n// ── {title} {'─' * fill}\n"


def render(ir: AppIR) -> str:
    parts: list[str] = [_render_header(ir)]

    # msgspec emits ``mod.Case`` when two modules each define ``Case``; otherwise
    # just ``Case``. Build a stable component-name → TS-identifier map so we can
    # rewrite ``$ref``s the same way in every type expression below.
    name_map = _disambiguate(ir.components.keys())

    # Errors and domain types live in the same `components` bucket. The IR knows
    # which names are errors via `route.raises`; everything else is "domain".
    error_names = {e.name for r in ir.routes for e in r.raises}

    domain_keys = sorted(k for k in ir.components if name_map[k] not in error_names)
    error_keys = sorted(k for k in ir.components if name_map[k] in error_names)

    if domain_keys:
        parts.append(_section("Domain types"))
        for raw in domain_keys:
            parts.append(
                f"export type {name_map[raw]} = {_render_type(ir.components[raw], name_map)};\n"
            )

    if error_keys:
        parts.append(_section("Errors"))
        for raw in error_keys:
            parts.append(
                f"export type {name_map[raw]} = {_render_type(ir.components[raw], name_map)};\n"
            )

    enum_block = _render_enum_consts(ir, name_map)
    if enum_block:
        parts.append(_section("Enum value-objects"))
        parts.append(enum_block)

    parts.append(_section("Client"))
    parts.append("interface ApiRoutes {\n")
    for route in ir.routes:
        parts.append("  " + _render_method_signature(route, name_map) + "\n")
    parts.append("}\n\n")

    parts.append("const _routes: ReadonlyArray<RouteDescriptor> = [\n")
    for route in ir.routes:
        parts.append("  " + _render_route_descriptor(route) + ",\n")
    parts.append("];\n\n")

    parts.append("export const api = createClient({ routes: _routes }) as ApiRoutes;\n")

    namespace = _render_routes_namespace(ir, name_map)
    if namespace:
        parts.append(_section("Per-route type aliases"))
        parts.append(namespace)
    return "".join(parts)


def _render_enum_consts(ir: AppIR, name_map: dict[str, str]) -> str:
    """Emit `<Struct><Field>` value-objects for every string-enum struct property.

    `transitionIssue({ to: IssueStatus.Closed })` refactors safely via IDE rename
    where the bare `"closed"` literal wouldn't. Skipped for the `kind`
    discriminator field (msgspec tag values) and any non-string enum.
    """
    consts: list[str] = []
    for raw in sorted(ir.components):
        props_any: Any = ir.components[raw].get("properties")
        if not isinstance(props_any, dict):
            continue
        props = cast("dict[str, Any]", props_any)
        struct_name = name_map.get(raw, _safe_ident(raw))
        for field_name, schema in props.items():
            if field_name == "kind" or not isinstance(schema, dict):
                continue
            values_any: Any = cast("dict[str, Any]", schema).get("enum")
            if not isinstance(values_any, list):
                continue
            values = cast("list[Any]", values_any)  # type: ignore[redundant-cast]
            if not all(isinstance(v, str) for v in values):
                continue
            str_values = cast("list[str]", values)
            entries = ", ".join(f"{_pascal(v)}: {json.dumps(v)}" for v in str_values)
            const_name = struct_name + _pascal(field_name)
            consts.append(f"export const {const_name} = {{ {entries} }} as const;\n")
    return "".join(consts)


def _render_routes_namespace(ir: AppIR, name_map: dict[str, str]) -> str:
    """Emit a type-only `Routes` namespace — one sub-namespace per route.

    Gives users `Routes.getIssue.Error`, `Routes.getIssue.Args`, etc., grouped
    by the route they came from. Pure type aliases; erased at runtime.
    """
    if not ir.routes:
        return ""
    out = ["export namespace Routes {\n"]
    for route in ir.routes:
        name = _safe_ident(_to_camel(route.name))
        out.append(f"  export namespace {name} {{\n")

        args_type, _ = _render_args_type(route.params, name_map)
        if args_type:
            out.append(f"    export type Args = {args_type};\n")

        if route.streams:
            event = _render_type(route.event_schema, name_map) if route.event_schema else "unknown"
            out.append(f"    export type Event = {event};\n")
            out.append("    export type Return = AsyncIterable<Event>;\n")
        else:
            data = _render_type(route.response, name_map) if route.response else "void"
            out.append(f"    export type Data = {data};\n")
            if route.raises:
                err = " | ".join(name_map.get(e.name, _safe_ident(e.name)) for e in route.raises)
                out.append(f"    export type Error = {err};\n")
                out.append("    export type Return = Promise<Result<Data, Error>>;\n")
            else:
                out.append("    export type Return = Promise<Data>;\n")

        out.append("  }\n")
    out.append("}\n")
    return "".join(out)


def _disambiguate(raw_keys: Iterable[str]) -> dict[str, str]:
    """Map raw component keys → TS identifiers, prefixing colliding short names.

    Unique types stay clean: ``Case`` → ``Case``. Collisions get the last
    ``.``-separated module segment in PascalCase: ``billing.Case`` → ``BillingCase``,
    ``legal.Case`` → ``LegalCase``. Stable across regenerations as long as the
    set of colliding modules doesn't change.
    """
    keys = list(raw_keys)
    by_short: dict[str, list[str]] = {}
    for k in keys:
        short = k.rsplit(".", 1)[-1]
        by_short.setdefault(short, []).append(k)

    out: dict[str, str] = {}
    for short, members in by_short.items():
        if len(members) == 1:
            out[members[0]] = _safe_ident(short)
            continue
        # Collision — prefix each with its last module segment, PascalCased.
        for full in members:
            head, _, tail = full.rpartition(".")
            prefix = head.rsplit(".", 1)[-1] if head else ""
            out[full] = _safe_ident(_pascal(prefix) + tail) if prefix else _safe_ident(tail)
    return out


def _pascal(name: str) -> str:
    return "".join(
        part[:1].upper() + part[1:] for part in name.replace("-", "_").split("_") if part
    )


def write(ir: AppIR, out: Path) -> None:
    """Atomic write — tmp + rename so the TS toolchain never reads a partial file."""
    tmp = out.with_suffix(out.suffix + ".tmp")
    tmp.parent.mkdir(parents=True, exist_ok=True)
    tmp.write_text(render(ir), encoding="utf-8")
    tmp.replace(out)


def _render_type(schema: Any, name_map: dict[str, str] | None = None) -> str:
    """Render a JSON Schema fragment as a TypeScript type expression."""
    if schema is None:
        return "void"
    if not isinstance(schema, dict):
        return "unknown"
    s = cast("dict[str, Any]", schema)

    if "$ref" in s:
        raw = str(s["$ref"]).rsplit("/", 1)[-1]
        if name_map is not None and raw in name_map:
            return name_map[raw]
        return _safe_ident(raw)
    if "const" in s:
        return json.dumps(s["const"])
    if "enum" in s:
        return " | ".join(json.dumps(v) for v in cast("list[Any]", s["enum"]))
    if "oneOf" in s:
        return " | ".join(_render_type(x, name_map) for x in s["oneOf"])
    if "anyOf" in s:
        return " | ".join(_render_type(x, name_map) for x in s["anyOf"])
    if "allOf" in s:
        return " & ".join(_render_type(x, name_map) for x in s["allOf"])

    t: Any = s.get("type")
    if isinstance(t, list):
        # Pylance treats list contents as Unknown without the cast; mypy thinks
        # the cast is redundant. We side with Pylance because the strict-mode
        # warning is what surfaces in the editor.
        ts = cast("list[Any]", t)  # type: ignore[redundant-cast]
        rest = {k: v for k, v in s.items() if k != "type"}
        return " | ".join(_render_type({"type": x, **rest}) for x in ts)

    if t == "string":
        return "Blob" if s.get("format") == "binary" else "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        if "prefixItems" in s:
            return "[" + ", ".join(_render_type(x) for x in s["prefixItems"]) + "]"
        items = s.get("items")
        return f"Array<{_render_type(items) if items else 'unknown'}>"
    if t == "object" or "properties" in s or "additionalProperties" in s:
        props = cast("dict[str, Any]", s.get("properties") or {})
        required_raw = cast("list[Any]", s.get("required") or [])
        required: set[str] = {_to_camel(str(k)) for k in required_raw}
        additional = s.get("additionalProperties")
        if not props and additional is not None and additional is not False:
            return f"Record<string, {_render_type(additional)}>"
        fields_out: list[str] = []
        for key, child in props.items():
            ts_key = _to_camel(str(key))
            opt = "" if ts_key in required else "?"
            fields_out.append(f"{_safe_key(ts_key)}{opt}: {_render_type(child)}")
        return "{ " + "; ".join(fields_out) + " }" if fields_out else "Record<string, never>"

    return "unknown"


def _render_method_signature(route: RouteIR, name_map: dict[str, str]) -> str:
    args_type, args_optional = _render_args_type(route.params, name_map)
    return_type = _render_return_type(route, name_map)
    name = _safe_ident(_to_camel(route.name))
    if args_type:
        return f"{name}(args{'?' if args_optional else ''}: {args_type}, opts?: CallOptions): {return_type};"
    return f"{name}(opts?: CallOptions): {return_type};"


def _render_args_type(params: list[ParamIR], name_map: dict[str, str]) -> tuple[str | None, bool]:
    if not params:
        return None, True
    fields_out: list[str] = []
    all_optional = True
    for p in params:
        if p.required:
            all_optional = False
        ts_name = _to_camel(p.name)
        fields_out.append(
            f"{_safe_key(ts_name)}{'' if p.required else '?'}: {_render_type(p.schema, name_map)}"
        )
    return "{ " + "; ".join(fields_out) + " }", all_optional


def _render_return_type(route: RouteIR, name_map: dict[str, str]) -> str:
    if route.streams:
        event = _render_type(route.event_schema, name_map) if route.event_schema else "unknown"
        return f"AsyncIterable<{event}>"
    data = _render_type(route.response, name_map) if route.response else "void"
    if route.raises:
        err = " | ".join(name_map.get(e.name, _safe_ident(e.name)) for e in route.raises)
        return f"Promise<Result<{data}, {err}>>"
    return f"Promise<{data}>"


def _render_route_descriptor(route: RouteIR) -> str:
    parts = [
        f"method: {json.dumps(route.method)}",
        f"path: {json.dumps(route.path)}",
        # ``name`` matches the camelCase method name on the TS side; ``alias``
        # on each param carries the snake_case wire key the Python server expects.
        f"name: {json.dumps(_to_camel(route.name))}",
    ]
    if route.params:
        rendered = [
            "{ "
            + f"name: {json.dumps(_to_camel(p.name))}, alias: {json.dumps(p.alias)}, in: {json.dumps(p.location)}"
            + (", embed: true" if p.embed else "")
            + " }"
            for p in route.params
        ]
        parts.append("params: [" + ", ".join(rendered) + "]")
    if route.streams:
        parts.append("streams: true")
    if route.raises:
        parts.append("result: true")
    if route.binary_body:
        parts.append("binaryBody: true")
    if route.binary_response:
        parts.append("binaryResponse: true")
    return "{ " + ", ".join(parts) + " }"


# ---- identifier hygiene ----
# msgspec emits valid Python class names but we defend against surprises
# (digits-first, hyphens) so the codegen can never produce invalid TS.

_IDENT_RE = re.compile(r"[^A-Za-z0-9_]")
_SAFE_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _safe_ident(name: str) -> str:
    cleaned = _IDENT_RE.sub("_", name)
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned or "_"


def _safe_key(key: str) -> str:
    if _SAFE_KEY_RE.match(key) and not keyword.iskeyword(key):
        return key
    return json.dumps(key)
