"""Polyglot client codegen — Swift and Kotlin renderers off the same IR.

Both renderers emit a working HTTP client: typed args, typed responses,
typed ``@raises`` error unions (as sealed enums / nested enums), and
JSON encoding/decoding that matches Tythe's snake_case wire format.

Scope notes:

- Streaming endpoints emit a method that returns ``URL``/``HttpUrl`` so
  callers can wire SSE through their platform's preferred client. Full
  AsyncIterable-style streaming would mean shipping an SSE parser per
  language; out of scope for v0.1.
- Swift uses URLSession + JSONEncoder/JSONDecoder.
- Kotlin uses HttpURLConnection + kotlinx.serialization. No ktor / OkHttp
  dependency — keep the generated file drop-in for any Gradle module.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, cast

from tythe._idents import to_camel as _to_camel
from tythe.ir import AppIR, RouteIR

# ---------- shared helpers ----------

_PRIMITIVES = {"string", "integer", "number", "boolean", "null"}


def _ref_name(schema: dict[str, Any]) -> str | None:
    ref = schema.get("$ref")
    if isinstance(ref, str):
        return ref.rsplit("/", 1)[-1]
    return None


def _is_null_schema(value: Any) -> bool:
    return isinstance(value, dict) and cast("dict[str, Any]", value).get("type") == "null"


# ---------- Swift ----------


_SWIFT_PREAMBLE = """\
// AUTO-GENERATED by `tythe`. Do not edit by hand. Re-run `tythe swift`.

import Foundation

public struct TytheClient {
    public let baseURL: URL
    public var defaultHeaders: [String: String]
    public let session: URLSession

    public init(
        baseURL: URL,
        defaultHeaders: [String: String] = [:],
        session: URLSession = .shared
    ) {
        self.baseURL = baseURL
        self.defaultHeaders = defaultHeaders
        self.session = session
    }

    fileprivate static let encoder: JSONEncoder = {
        let e = JSONEncoder()
        e.keyEncodingStrategy = .convertToSnakeCase
        return e
    }()

    fileprivate static let decoder: JSONDecoder = {
        let d = JSONDecoder()
        d.keyDecodingStrategy = .convertFromSnakeCase
        return d
    }()
}

public enum TytheRPCError: Error {
    case http(status: Int, body: Data)
    case decode(Error)
    case transport(Error)
}

public enum TytheResult<Success, Failure> {
    case ok(Success)
    case err(Failure)
}
"""


def render_swift(ir: AppIR) -> str:
    parts: list[str] = [_SWIFT_PREAMBLE]
    for name in sorted(ir.components):
        parts.append(_swift_struct(name.rsplit(".", 1)[-1], ir.components[name]))

    for method_name, variants in _collect_error_unions(ir).items():
        parts.append(_swift_error_enum(method_name, variants))

    parts.append("public extension TytheClient {\n")
    for route in ir.routes:
        parts.append(_swift_method(route))
    parts.append("}\n")
    return "".join(parts)


def write_swift(ir: AppIR, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_swift(ir), encoding="utf-8")


def _swift_struct(name: str, schema: dict[str, Any]) -> str:
    props_any: Any = schema.get("properties")
    if not isinstance(props_any, dict):
        return ""
    props = cast("dict[str, Any]", props_any)
    required = cast("list[str]", schema.get("required") or [])
    ident = _swift_ident(name)
    lines = [f"public struct {ident}: Codable {{\n"]
    for raw_name, child in props.items():
        is_required = raw_name in required
        camel = _to_camel(raw_name)
        ty = _swift_type(child)
        if not is_required:
            ty = f"{ty}?"
        lines.append(f"    public let {camel}: {ty}\n")
    lines.append("}\n\n")
    return "".join(lines)


def _swift_error_enum(method_name: str, variants: list[str]) -> str:
    enum_name = _swift_error_enum_name(method_name)
    out = [f"public enum {enum_name}: Error {{\n"]
    for v in variants:
        out.append(f"    case {_lower_first(v)}({_swift_ident(v)})\n")
    out.append("\n    static func decode(kind: String, data: Data) throws -> ")
    out.append(f"{enum_name} {{\n")
    out.append("        switch kind {\n")
    for v in variants:
        out.append(f'        case "{v}": return .{_lower_first(v)}(try TytheClient.decoder.decode')
        out.append(f"({_swift_ident(v)}.self, from: data))\n")
    out.append('        default: throw TytheRPCError.decode(NSError(domain: "tythe", code: 0))\n')
    out.append("        }\n")
    out.append("    }\n")
    out.append("}\n\n")
    return "".join(out)


def _swift_method(route: RouteIR) -> str:
    method = _swift_ident(_to_camel(route.name))
    args = [(_to_camel(p.name), _swift_type(p.schema)) for p in route.params]
    body_params = [p for p in route.params if p.location == "body"]
    has_raises = bool(route.raises)
    ret_ty = _swift_response_type(route)

    arg_list = ", ".join(f"{n}: {t}" for n, t in args)
    head = f"    func {method}({arg_list}) async throws -> {ret_ty} {{\n"

    body: list[str] = [head]
    # URL build
    body.append(f'        var path = "{route.path}"\n')
    for p in route.params:
        if p.location == "path":
            body.append(
                f'        path = path.replacingOccurrences(of: "{{{p.alias}}}", '
                f'with: "\\({_to_camel(p.name)})")\n'
            )
    body.append("        var components = URLComponents(\n")
    body.append("            url: baseURL.appendingPathComponent(path),\n")
    body.append("            resolvingAgainstBaseURL: false\n")
    body.append("        )!\n")

    queries = [p for p in route.params if p.location == "query"]
    if queries:
        body.append("        var items: [URLQueryItem] = []\n")
        for p in queries:
            body.append(
                f'        items.append(URLQueryItem(name: "{p.alias}", '
                f'value: "\\({_to_camel(p.name)})"))\n'
            )
        body.append("        components.queryItems = items\n")

    body.append("        var req = URLRequest(url: components.url!)\n")
    body.append(f'        req.httpMethod = "{route.method}"\n')
    body.append("        for (k, v) in defaultHeaders { req.setValue(v, forHTTPHeaderField: k) }\n")
    for p in route.params:
        if p.location == "header":
            body.append(
                f'        req.setValue("\\({_to_camel(p.name)})", '
                f'forHTTPHeaderField: "{p.alias}")\n'
            )
        elif p.location == "cookie":
            body.append(
                f'        req.setValue("{p.alias}=\\({_to_camel(p.name)})", '
                f'forHTTPHeaderField: "Cookie")\n'
            )

    if body_params:
        if len(body_params) == 1 and not body_params[0].embed:
            payload = _to_camel(body_params[0].name)
            body.append(
                '        req.setValue("application/json", forHTTPHeaderField: "Content-Type")\n'
            )
            body.append(f"        req.httpBody = try TytheClient.encoder.encode({payload})\n")
        else:
            body.append("        struct _Body: Encodable {\n")
            for p in body_params:
                body.append(f"            let {_to_camel(p.name)}: {_swift_type(p.schema)}\n")
            body.append("        }\n")
            ctor = ", ".join(f"{_to_camel(p.name)}: {_to_camel(p.name)}" for p in body_params)
            body.append(f"        let _b = _Body({ctor})\n")
            body.append(
                '        req.setValue("application/json", forHTTPHeaderField: "Content-Type")\n'
            )
            body.append("        req.httpBody = try TytheClient.encoder.encode(_b)\n")

    # Send + decode
    body.append("        let (data, response) = try await session.data(for: req)\n")
    body.append("        guard let http = response as? HTTPURLResponse else {\n")
    body.append('            throw TytheRPCError.transport(NSError(domain: "tythe", code: 0))\n')
    body.append("        }\n")
    body.append("        guard (200..<300).contains(http.statusCode) else {\n")
    body.append("            throw TytheRPCError.http(status: http.statusCode, body: data)\n")
    body.append("        }\n")

    if has_raises:
        enum_name = _swift_error_enum_name(route.name)
        success_ty = _swift_response_type(route)
        body.append("        struct _Env: Decodable { let ok: Bool; let kind: String? }\n")
        body.append(
            "        let env = (try? TytheClient.decoder.decode(_Env.self, from: data)) ?? _Env(ok: true, kind: nil)\n"
        )
        body.append("        if !env.ok {\n")
        body.append("            struct _Err: Decodable { let error: [String: AnyCodable] }\n")
        body.append("            throw try {() -> Error in\n")
        body.append(
            "                let raw = try JSONSerialization.jsonObject(with: data) as? [String: Any]\n"
        )
        body.append('                let errBlob = raw?["error"] as? [String: Any] ?? [:]\n')
        body.append('                let kind = errBlob["kind"] as? String ?? ""\n')
        body.append(
            "                let payload = try JSONSerialization.data(withJSONObject: errBlob)\n"
        )
        body.append(f"                return try {enum_name}.decode(kind: kind, data: payload)\n")
        body.append("            }()\n")
        body.append("        }\n")
        body.append("        struct _Ok: Decodable { let data: " + success_ty + " }\n")
        body.append("        let ok = try TytheClient.decoder.decode(_Ok.self, from: data)\n")
        body.append("        return .ok(ok.data)\n")
    else:
        success_ty = _swift_response_type(route)
        if success_ty == "Void":
            body.append("        _ = data\n")
            body.append("        return\n")
        else:
            body.append(
                f"        return try TytheClient.decoder.decode({success_ty}.self, from: data)\n"
            )

    body.append("    }\n\n")
    return "".join(body)


def _swift_response_type(route: RouteIR) -> str:
    if route.streams:
        return "URLRequest"
    if route.response is None:
        return "Void"
    return _swift_type(route.response)


def _swift_error_enum_name(method_name: str) -> str:
    return _swift_ident(_to_camel(method_name)[:1].upper() + _to_camel(method_name)[1:]) + "Error"


def _collect_error_unions(ir: AppIR) -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for route in ir.routes:
        if route.raises:
            out[route.name] = [e.name for e in route.raises]
    return out


def _swift_type(schema: Any) -> str:
    if not isinstance(schema, dict):
        return "AnyCodable"
    s = cast("dict[str, Any]", schema)
    ref = _ref_name(s)
    if ref is not None:
        return _swift_ident(ref)
    t = s.get("type")
    if isinstance(t, list):
        # nullable: ["string", "null"]
        non_null_t = [x for x in cast("list[Any]", t) if x != "null"]  # type: ignore[redundant-cast]
        if non_null_t:
            inner = _swift_type(
                {"type": non_null_t[0], **{k: v for k, v in s.items() if k != "type"}}
            )
            return f"{inner}?"
        return "AnyCodable?"
    if t == "string":
        return "String"
    if t == "integer":
        return "Int"
    if t == "number":
        return "Double"
    if t == "boolean":
        return "Bool"
    if t == "array":
        items = s.get("items")
        return f"[{_swift_type(items)}]"
    if "anyOf" in s or "oneOf" in s:
        variants = cast("list[Any]", s.get("anyOf") or s.get("oneOf"))
        non_null_v: list[Any] = [v for v in variants if not _is_null_schema(v)]
        if len(non_null_v) == 1:
            return f"{_swift_type(non_null_v[0])}?"
        return "AnyCodable"
    return "AnyCodable"


def _swift_ident(name: str) -> str:
    cleaned = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
    return cleaned or "_"


def _lower_first(name: str) -> str:
    return name[:1].lower() + name[1:] if name else name


# ---------- Kotlin ----------


_KOTLIN_PREAMBLE_TEMPLATE = """\
// AUTO-GENERATED by `tythe`. Do not edit by hand. Re-run `tythe kotlin`.

package {package}

import java.net.HttpURLConnection
import java.net.URL
import java.net.URLEncoder
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

internal val tytheJson = Json {{ ignoreUnknownKeys = true }}

class TytheRPCError(val status: Int, val body: String) : RuntimeException("HTTP $status")

class TytheClient(
    private val baseUrl: String,
    private val defaultHeaders: Map<String, String> = emptyMap(),
) {{
    internal suspend fun request(
        method: String,
        path: String,
        query: List<Pair<String, String>> = emptyList(),
        headers: Map<String, String> = emptyMap(),
        body: String? = null,
    ): String = withContext(Dispatchers.IO) {{
        val qs = if (query.isEmpty()) "" else "?" + query.joinToString("&") {{ (k, v) ->
            URLEncoder.encode(k, "UTF-8") + "=" + URLEncoder.encode(v, "UTF-8")
        }}
        val url = URL(baseUrl.trimEnd('/') + path + qs)
        val conn = (url.openConnection() as HttpURLConnection).apply {{
            requestMethod = method
            for ((k, v) in defaultHeaders) setRequestProperty(k, v)
            for ((k, v) in headers) setRequestProperty(k, v)
            if (body != null) {{
                doOutput = true
                setRequestProperty("Content-Type", "application/json")
                outputStream.use {{ it.write(body.toByteArray(Charsets.UTF_8)) }}
            }}
        }}
        val status = conn.responseCode
        val stream = if (status in 200..299) conn.inputStream else conn.errorStream
        val text = stream?.bufferedReader()?.use {{ it.readText() }} ?: ""
        if (status !in 200..299) throw TytheRPCError(status, text)
        text
    }}
"""

_KOTLIN_END = "}\n"


def render_kotlin(ir: AppIR, *, package: str = "com.tythe.generated") -> str:
    parts: list[str] = [_KOTLIN_PREAMBLE_TEMPLATE.format(package=package)]
    # Methods live inside the TytheClient class, so we close it after methods.

    for route in ir.routes:
        parts.append(_kotlin_method(route))

    parts.append(_KOTLIN_END)

    # Data classes + sealed-class error unions go after.
    for name in sorted(ir.components):
        parts.append(_kotlin_data_class(name.rsplit(".", 1)[-1], ir.components[name]))

    for method_name, variants in _collect_error_unions(ir).items():
        parts.append(_kotlin_error_sealed(method_name, variants))

    return "".join(parts)


def write_kotlin(ir: AppIR, out: Path, *, package: str = "com.tythe.generated") -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_kotlin(ir, package=package), encoding="utf-8")


def _kotlin_data_class(name: str, schema: dict[str, Any]) -> str:
    props_any: Any = schema.get("properties")
    if not isinstance(props_any, dict):
        return ""
    props = cast("dict[str, Any]", props_any)
    required = cast("list[str]", schema.get("required") or [])
    ident = _kotlin_ident(name)
    fields_out: list[str] = []
    for raw_name, child in props.items():
        is_required = raw_name in required
        camel = _to_camel(raw_name)
        ty = _kotlin_type(child)
        if not is_required:
            ty = f"{ty}? = null"
        ann = f'@SerialName("{raw_name}") ' if camel != raw_name else ""
        fields_out.append(f"    {ann}val {camel}: {ty}")
    body = ",\n".join(fields_out)
    return f"@Serializable\ndata class {ident}(\n{body}\n)\n\n"


def _kotlin_error_sealed(method_name: str, variants: list[str]) -> str:
    name = _kotlin_error_enum_name(method_name)
    out = [f"sealed class {name} : RuntimeException() {{\n"]
    for v in variants:
        out.append(
            f"    data class Is{_kotlin_ident(v)}(val payload: {_kotlin_ident(v)}) : {name}()\n"
        )
    out.append("}\n\n")
    return "".join(out)


def _kotlin_method(route: RouteIR) -> str:
    method = _kotlin_ident(_to_camel(route.name))
    arg_list = ", ".join(f"{_to_camel(p.name)}: {_kotlin_type(p.schema)}" for p in route.params)
    return_ty = _kotlin_response_type(route)
    if route.raises:
        return_ty += f" /* may throw {_kotlin_error_enum_name(route.name)} */"

    out: list[str] = []
    out.append(f"    suspend fun {method}({arg_list}): {return_ty} {{\n")

    # Path with substitutions
    out.append(f'        var path = "{route.path}"\n')
    for p in route.params:
        if p.location == "path":
            out.append(
                f'        path = path.replace("{{{p.alias}}}", {_to_camel(p.name)}.toString())\n'
            )

    # Query
    queries = [p for p in route.params if p.location == "query"]
    if queries:
        out.append("        val query = listOf(\n")
        for p in queries:
            out.append(f'            "{p.alias}" to {_to_camel(p.name)}.toString(),\n')
        out.append("        )\n")
    else:
        out.append("        val query = emptyList<Pair<String, String>>()\n")

    # Headers
    headers = [p for p in route.params if p.location == "header"]
    cookies = [p for p in route.params if p.location == "cookie"]
    if headers or cookies:
        out.append("        val headers = buildMap<String, String> {\n")
        for p in headers:
            out.append(f'            put("{p.alias}", {_to_camel(p.name)}.toString())\n')
        for p in cookies:
            out.append(
                f'            put("Cookie", "{p.alias}=" + {_to_camel(p.name)}.toString())\n'
            )
        out.append("        }\n")
    else:
        out.append("        val headers = emptyMap<String, String>()\n")

    # Body
    body_params = [p for p in route.params if p.location == "body"]
    if body_params:
        if len(body_params) == 1 and not body_params[0].embed:
            payload = _to_camel(body_params[0].name)
            out.append(f"        val body = tytheJson.encodeToString({payload})\n")
        else:
            entries = ", ".join(
                f'"{p.alias}" to tytheJson.encodeToJsonElement({_to_camel(p.name)})'
                for p in body_params
            )
            out.append(
                f"        val body = tytheJson.encodeToString(JsonObject(mapOf({entries})))\n"
            )
    else:
        out.append("        val body: String? = null\n")

    out.append(f'        val resp = request("{route.method}", path, query, headers, body)\n')

    if route.streams:
        out.append("        return resp\n")
    elif route.response is None:
        out.append("        return\n")
    elif route.raises:
        success_ty = _kotlin_type(route.response)
        enum_name = _kotlin_error_enum_name(route.name)
        out.append("        val env = tytheJson.parseToJsonElement(resp).jsonObject\n")
        out.append('        val ok = env["ok"]?.jsonPrimitive?.content == "true"\n')
        out.append("        if (ok) {\n")
        out.append(
            f'            return tytheJson.decodeFromJsonElement<{success_ty}>(env["data"]!!)\n'
        )
        out.append("        }\n")
        out.append('        val err = env["error"]!!.jsonObject\n')
        out.append('        val kind = err["kind"]!!.jsonPrimitive.content\n')
        out.append("        when (kind) {\n")
        for v in route.raises:
            out.append(
                f'            "{v.name}" -> throw {enum_name}.Is{_kotlin_ident(v.name)}('
                f"tytheJson.decodeFromJsonElement(err))\n"
            )
        out.append("            else -> throw TytheRPCError(500, resp)\n")
        out.append("        }\n")
    else:
        success_ty = _kotlin_type(route.response)
        out.append(f"        return tytheJson.decodeFromString<{success_ty}>(resp)\n")

    out.append("    }\n\n")
    return "".join(out)


def _kotlin_response_type(route: RouteIR) -> str:
    if route.streams:
        return "String"  # raw SSE; caller parses
    if route.response is None:
        return "Unit"
    return _kotlin_type(route.response)


def _kotlin_error_enum_name(method_name: str) -> str:
    return _kotlin_ident(_to_camel(method_name)[:1].upper() + _to_camel(method_name)[1:]) + "Error"


def _kotlin_type(schema: Any) -> str:
    if not isinstance(schema, dict):
        return "kotlinx.serialization.json.JsonElement"
    s = cast("dict[str, Any]", schema)
    ref = _ref_name(s)
    if ref is not None:
        return _kotlin_ident(ref)
    t = s.get("type")
    if isinstance(t, list):
        non_null_t = [x for x in cast("list[Any]", t) if x != "null"]  # type: ignore[redundant-cast]
        if non_null_t:
            inner = _kotlin_type(
                {"type": non_null_t[0], **{k: v for k, v in s.items() if k != "type"}}
            )
            return f"{inner}?"
        return "kotlinx.serialization.json.JsonElement?"
    if t == "string":
        return "String"
    if t == "integer":
        return "Long"
    if t == "number":
        return "Double"
    if t == "boolean":
        return "Boolean"
    if t == "array":
        items = s.get("items")
        return f"List<{_kotlin_type(items)}>"
    if "anyOf" in s or "oneOf" in s:
        variants = cast("list[Any]", s.get("anyOf") or s.get("oneOf"))
        non_null_k: list[Any] = [v for v in variants if not _is_null_schema(v)]
        if len(non_null_k) == 1:
            return f"{_kotlin_type(non_null_k[0])}?"
        return "kotlinx.serialization.json.JsonElement"
    return "kotlinx.serialization.json.JsonElement"


def _kotlin_ident(name: str) -> str:
    cleaned = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
    return cleaned or "_"
